language: node_js
node_js:
  - "stable"
services:
  - docker

script:
  - echo "aze"
  - env
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo $TRAVIS_PULL_REQUEST
  #- docker build .

after_success:
  - ./get_next_tag.sh $TRAVIS_BRANCH $(git describe --abbrev=0)