language: node_js
node_js:
  - "stable"
services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - echo "Testing stage" && return 0
    - stage: deploy
      script:
        - sudo apt install gawk
        - export NEXT_TAG=$(./get_next_tag.sh $TRAVIS_PULL_REQUEST_BRANCH $(git describe --abbrev=0))
        - echo "Next version = $NEXT_TAG"
        - docker build -t yuruh/encrypted-diary-web-app:$NEXT_TAG .
        - docker login -u yuruh -p $DOCKER_PWD
        - git tag -a $NEXT_TAG -m "$TRAVIS_COMMIT_MESSAGE"
        - git push "https://$GITHUB_TOKEN@github.com/Yuruh/encrypted-diary-web-app.git --tags
        - docker push yuruh/encrypted-diary-web-app:$NEXT_TAG

stages:
  - name: test
  - name: deploy
    if: branch = master