language: node_js
node_js:
  - "stable"
services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - echo "Testing stage" && return 0
    - stage: deploy
      script:
        # Installing gawk to get platform agnostic usage of command AWK
        - sudo apt install gawk

        # Computing next tag name based on branch name
        - export NEXT_TAG=$(./get_next_tag.sh $TRAVIS_PULL_REQUEST_BRANCH $(git describe --abbrev=0))
        - echo "Next version = $NEXT_TAG"
        - docker build -t yuruh/encrypted-diary-web-app:$NEXT_TAG .
        - docker login -u yuruh -p $DOCKER_PWD
        - git tag -a $NEXT_TAG -m "Merge from pull request $TRAVIS_PULL_REQUEST"
        - git push "https://$GITHUB_TOKEN@github.com/Yuruh/encrypted-diary-web-app.git" --tags
        - docker push yuruh/encrypted-diary-web-app:$NEXT_TAG

stages:
  - name: test
  - name: deploy
    if: branch = master # && $TRAVIS_PULL_REQUEST != "false"