language: node_js
node_js:
  - "stable"
services:
  - docker

script:
  - echo "aze"
  - env
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo $TRAVIS_PULL_REQUEST
  #- docker build .

jobs:
  include:
    - stage: test
      script: echo "Testing stage"
    - stage: deploy
      script: ./get_next_tag.sh $TRAVIS_BRANCH $(git describe --abbrev=0)

stages:
  - name: deploy
    if: branch = master